### ISSUE TITLE
Getting an issue with ListAllCategoryRarities

### ISSUE THREAD

**Issue by TrexKikBut** [tyronbrand/TCGPlayer.Net#2]
Hello. I just started using this package, and it has been working for most of the stuff. Tried to get CategoryRarities and it messed up. 

**Here is the error:**
`TCGPlayer.Net.TcgApiException: 'Exception of type 'TCGPlayer.Net.TcgApiException' was thrown.'`

**Here is my code:**

```
public static async Task GetAllRarities(int categoryIdNum)
        {
            var token = await Auth.Authenticate.GetToken();
            var apiService = TcgApiService.CreateDefaultApi(token);

            var @params = new ListAllCategoryRaritiesGETRequestParams
            {
                CategoryId = categoryIdNum,
            };

            var result = await apiService.Execute(TcgApiUrls.Catalog.ListAllCategoryRarities, @params);
}`

**Comment by TrexKikBut** [comment]
The error is because some categories don't have any rarities. So when TcgApiResult doesn't return anything, it throws out an error. Was able to make a way around it to get it to work.

**Comment by tyronbrand** [comment]
I shall investigate the issue this evening, thanks @TrexKikBut

**Comment by TrexKikBut** [comment]
Thank you! I've noticed a lot of them doing that. I have also ran into an issue with grabbing SKUs. Sometimes the SKUs return a null conditionId and it breaks everything.

**Comment by tyronbrand** [comment]
Hey @TrexKikBut,

Please update to the latest nuget package and create a new ticket if you're still having an issue or any questions.

Thanks
